id: I0FB1AC0C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:25:38+00:00'
last_modified: '2022-06-07T12:33:11.601140+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD386
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་། གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  base:
    DDEA:
      image_group_id: I2PD17837
      title: ''
      total_pages: 132
      order: 1
      base_file: DDEA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
