id: P000648
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD386
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་། གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  volumes:
    213dc738317846dea916ae08f0f4c563:
      image_group_id: I2PD17837
      title: ''
      volume_number: 1
      total_pages: 132
