id: P000648
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3PD386
  title: གླིང་རྗེ་གེ་སར་རྒྱལ་པོའི་སྒྲུང་། གྱི་ལིང་བཅུ་གསུམ་འབྱུང་ཁུངས་སྐོར།
  author: ''
  volumes:
    213dc738317846dea916ae08f0f4c563:
      image_group_id: I2PD17837
      title: ''
      volume_number: 1
      total_pages: 132
